import test from 'node:test';import assert from 'node:assert/strict';
// @ts-ignore Node executes this TypeScript module directly during the test run.
import{initialState,schedule,progressKey,makeSession,recordAnswer,addAttempt,applyGrade,resumeAfterGap,dateKey,daily,validBackup,dueTasks}from'../lib/learning.ts';
const now=new Date('2026-10-03T10:00:00').getTime();const day=86400000;
const words=['time','friend','choose','think'].map((word,i)=>({word,phonetic:'',level:'easy',topic:'',question:'',reflection:'',senses:[{id:word+'-1',meaning:['时间','朋友','选择','思考'][i],pos:'n.',example:'',translation:'',prompt:'',hint:''}]}));
test('recognition, listening, and sentence progress remain independent',()=>{const s=initialState();schedule(s,'time','time-1','read',true,now);assert.equal(s.progress[progressKey('time','time-1','read')].level,1);assert.equal(s.progress[progressKey('time','time-1','listen')],undefined);assert.equal(s.progress[progressKey('time','time-1','read')].due,now+day)});
test('overdue review fills time and suppresses new material',()=>{const s=initialState();for(const w of words.slice(0,3))schedule(s,w.word,w.senses[0].id,'read',false,now-100000);const session=makeSession(s,words,5,'mixed',now);assert.equal(session.queue.length,2);assert.ok(session.queue.every(t=>t.kind!=='new'))});
test('two failures insert a previously known easy word, not an untested word',()=>{const s=initialState();schedule(s,'time','time-1','read',true,now);s.session=makeSession(s,words,5,'mixed',now);recordAnswer(s,false,words);recordAnswer(s,false,words);assert.equal(s.session.queue[1].kind,'comfort');assert.equal(s.session.queue[1].word,'time')});
test('three failures in five remove only future new cards',()=>{const s=initialState();s.session=makeSession(s,words,15,'mixed',now);for(const result of[false,true,false,true,false])recordAnswer(s,result,words);assert.ok(s.session.queue.slice(s.session.index+1).every(t=>t.kind!=='new'))});
test('offline submissions stay pending; delayed grades preserve original date and last study date',()=>{const s=initialState();const task={word:'time',senseId:'time-1',kind:'new' as const};const a=addAttempt(s,task,words[0],words[0].senses[0],'I have time.',now);assert.equal(a.status,'pending');assert.equal(Object.keys(s.progress).length,0);applyGrade(s,a.id,{wordCorrect:true,grammarCorrect:true,correction:'I have time.',explanation:'正确'},now+day*2);assert.equal(a.date,dateKey(now));assert.equal(s.lastStudyDate,dateKey(now));assert.equal(s.daily[dateKey(now+day*2)],undefined);assert.equal(a.status,'correct')});
test('a retry can resolve its original mistake without deleting it; duplicate grade is idempotent',()=>{const s=initialState();const task={word:'time',senseId:'time-1',kind:'new' as const};const a=addAttempt(s,task,words[0],words[0].senses[0],'I has time.',now);applyGrade(s,a.id,{wordCorrect:true,grammarCorrect:false,correction:'I have time.',explanation:'主谓一致'},now);const b=addAttempt(s,{...task,retryOf:a.id},words[0],words[0].senses[0],'I have time.',now+1000);const g={wordCorrect:true,grammarCorrect:true,correction:'I have time.',explanation:'正确'};applyGrade(s,b.id,g,now+2000);applyGrade(s,b.id,g,now+3000);assert.equal(a.resolvedAt,now+2000);assert.equal(s.attempts.length,2);assert.equal(s.progress[progressKey('time','time-1','write')].correct,1)});
test('only three complete missed calendar days trigger weekly restart and history survives',()=>{const s=initialState();schedule(s,'time','time-1','read',true,now);assert.equal(resumeAfterGap(s,now+day*3),false);assert.equal(resumeAfterGap(s,now+day*4),true);assert.deepEqual(s.recovery?.words,['time']);assert.equal(s.progress[progressKey('time','time-1','read')].level,1);assert.equal(resumeAfterGap(s,now+day*4+1000),false)});
test('new-word quota counts new words, not existing review words',()=>{const s=initialState();s.settings.newLimit=1;schedule(s,'time','time-1','read',true,now-day*2);schedule(s,'time','time-1','read',true,now);const session=makeSession(s,words,15,'mixed',now);assert.equal(session.queue.filter(t=>t.kind==='new').length,1)});
test('backup validation rejects corrupted progress and accepts normal state',()=>{const s=initialState();assert.ok(validBackup(s));assert.equal(validBackup({...s,progress:{x:{level:'bad'}}}),false);assert.equal(validBackup({...s,attempts:[{id:'x',status:'pending'}]}),false)});
test('pending grading never creates a wrong-answer review',()=>{const s=initialState();addAttempt(s,{word:'time',senseId:'time-1',kind:'new'},words[0],words[0].senses[0],'I have time.',now);assert.equal(dueTasks(s,words,now).length,0)});
test('pending retries stop repeated sentence tasks while preserving due recognition and listening',()=>{
 const s=initialState(),w=words[0],sense=w.senses[0],task={word:w.word,senseId:sense.id,kind:'new' as const};
 const original=addAttempt(s,task,w,sense,'I has time.',now);
 applyGrade(s,original.id,{wordCorrect:true,grammarCorrect:false,correction:'I have time.',explanation:'主谓一致'},now);
 const retry=addAttempt(s,{...task,retryOf:original.id},w,sense,'I have time.',now+1000);
 assert.equal(dueTasks(s,words,now+120000).length,0);
 assert.equal(makeSession(s,words,5,'errors',now+120000).queue.length,0);
 assert.ok(makeSession(s,words,5,'mixed',now+120000).queue.every(t=>t.word!==w.word));
 schedule(s,w.word,sense.id,'read',false,now);
 assert.equal(dueTasks(s,words,now+120000)[0].kind,'review');
 schedule(s,w.word,sense.id,'read',true,now+120000);
 applyGrade(s,retry.id,{wordCorrect:false,grammarCorrect:false,correction:'I have time.',explanation:'再试一次'},now+120000);
 assert.equal(dueTasks(s,words,now+120001)[0].kind,'error');
});
test('another five-minute session remains available after earlier learning time',()=>{const s=initialState();daily(s,now).seconds=600;assert.ok(makeSession(s,words,5,'mixed',now).queue.length>0)});
test('an error arriving during a review is linked when the new sentence is submitted',()=>{
 const s=initialState(),w=words[0],sense=w.senses[0],task={word:w.word,senseId:sense.id,kind:'review' as const};
 const first=addAttempt(s,task,w,sense,'I has time.',now);
 applyGrade(s,first.id,{wordCorrect:true,grammarCorrect:false,correction:'I have time.',explanation:'主谓一致'},now+1000);
 const retry=addAttempt(s,task,w,sense,'I have time.',now+2000);
 assert.equal(retry.retryOf,first.id);
 applyGrade(s,retry.id,{wordCorrect:true,grammarCorrect:true,correction:'I have time.',explanation:'正确'},now+3000);
 assert.equal(first.resolvedAt,now+3000);assert.equal(dueTasks(s,words,now+3001).length,0);
});
test('backup preserves unfinished sentence and rejects malformed recovery',()=>{const s=initialState();s.session=makeSession(s,words,5,'mixed',now);s.session.phase='write';s.session.draft='I choose to';assert.ok(validBackup(JSON.parse(JSON.stringify(s))));assert.equal(validBackup({...s,recovery:{words:42,started:'bad',until:null}}),false)});
