"use client";
import {useEffect,useState} from 'react';
import {BookOpen,Headphones,Pause,Check,Feather,ChevronLeft,ChevronRight} from 'lucide-react';
import {dailyIndex,type ReadingCollection,type ReadingProgress,type FeedbackKind} from '../lib/enrichment';

export default function DailyReading({data,date,progress,onAnswer,onDraft,onOpenWord,onPlay,onFeedback,playingId,selectedId,onSelect}:{data:ReadingCollection|null;selectedId?:string;onSelect:(id:string)=>void;playingId:string|null;date:string;progress:Record<string,ReadingProgress>;onAnswer:(id:string,answer:number,expected:number)=>void;onDraft:(id:string,draft:string)=>void;onOpenWord:(word:string)=>void;onPlay:(id:string,text:string)=>void;onFeedback:(kind:FeedbackKind)=>void}){
 const[translations,setTranslations]=useState(false);
 const readings=data?.readings||[];const selected=readings.findIndex(r=>r.id===selectedId);const current=selected>=0?selected:dailyIndex(date,readings.length);const article=readings[current];const saved=article?progress[article.id]:undefined;
 useEffect(()=>setTranslations(false),[article?.id]);
 if(!article)return <section className="panel empty-state"><BookOpen size={32}/><h2>每日短文正在准备</h2><p>联网打开一次后，文章和练习就能留在手机里。</p></section>;
 const wordCount=article.paragraphs.map(p=>p.en).join(' ').split(/\s+/).length;
 function answer(i:number){if(saved?.answer!==undefined)return;onAnswer(article.id,i,article.question.answerIndex);onFeedback(i===article.question.answerIndex?'correct':'wrong')}
 return <div className="reading-layout"><section className="reading-main"><header className="reading-title"><div className="eyebrow">每日一篇 · {article.theme}</div><h1>{article.title}</h1><h2>{article.titleEn}</h2><div className="reading-meta"><span>约 {wordCount} 词 · {Math.ceil(wordCount/70)} 分钟</span><span>原创 · 四级基础练习</span></div></header>
 <div className="reading-controls"><button className="button quiet" onClick={()=>onPlay(article.id,article.paragraphs.map(p=>p.en).join('\n'))}>{playingId===article.id?<Pause size={18}/>:<Headphones size={18}/>} {playingId===article.id?'暂停朗读':'听整篇'}</button><label className="checkbox-label"><input type="checkbox" checked={translations} onChange={e=>setTranslations(e.target.checked)}/>显示中文对照</label></div>
 <article className="reading-body">{article.paragraphs.map((p,i)=><section key={i}><p lang="en">{p.en}</p>{translations&&<p className="reading-translation">{p.zh}</p>}</section>)}</article>
 <div className="reading-phrase"><span><Feather size={17}/>可以带进写作的一个表达</span><blockquote>{article.phrase.phrase}<small>{article.phrase.translation}</small></blockquote></div>
 <section className="reading-quiz"><div className="section-heading"><span>停一下，想一想</span>{saved?.correct&&<span className="status-tag success"><Check size={14}/>已通过</span>}</div><h3>{article.question.question}</h3><div>{article.question.options.map((option,i)=><button key={option} disabled={saved?.answer!==undefined} className={`reading-option ${saved?.answer!==undefined?(i===article.question.answerIndex?'answer-right':i===saved.answer?'answer-wrong':''):''}`} onClick={()=>answer(i)}><span>{String.fromCharCode(65+i)}</span>{option}</button>)}</div>{saved?.answer!==undefined&&<p className="reading-explanation">{article.question.explanation}</p>}{saved?.answer!==undefined&&<button className="text-button" onClick={()=>onAnswer(article.id,-1,article.question.answerIndex)}>{saved.correct?'再自测一次':'再读一遍，再答一次'}</button>}</section>
 <section className="reading-note"><label htmlFor="reading-draft">{article.writingPrompt}</label><textarea id="reading-draft" value={saved?.draft||''} maxLength={1000} placeholder="从文中的一个词出发，写下你的想法…" onChange={e=>onDraft(article.id,e.target.value)}/><small>自动保存在本机 · 这里是阅读随笔，尚未进行 AI 批改</small></section>
 <div className="reading-today"><button className="text-button" onClick={()=>onSelect(readings[dailyIndex(date,readings.length)].id)}>回到今日推荐</button></div><div className="reading-pagination"><button className="text-button" onClick={()=>onSelect(readings[(current-1+readings.length)%readings.length].id)}><ChevronLeft size={17}/>上一篇</button><span>{current+1} / {readings.length}</span><button className="text-button" onClick={()=>onSelect(readings[(current+1)%readings.length].id)}>下一篇<ChevronRight size={17}/></button></div>
 </section><aside className="reading-sidebar panel"><div className="section-heading"><span><BookOpen size={17}/>读完，留下这几个词</span></div><p className="muted">点开词义、派生词和联想，再把它用进一句话。</p>{article.keywords.map(k=><button className="reading-keyword" key={k.word} onClick={()=>onOpenWord(k.word)}><strong>{k.word}</strong><span>{k.meaning}</span><ChevronRight size={17}/></button>)}<p className="family-source">短文按难度和词汇学习目标原创编写，不是历年真题。</p></aside></div>
}
